#!/usr/bin/env python3
"""
Fig 1G — LDLR clinical severity validation (Mayo Tapestry × EVEE).

Per-tier violin of EVEE Pathogenicity scores across three FH severity tiers
(Clinical FH, Suspected FH, Presymptomatic carrier) for 147 LDLR variants
from the Mayo Clinic Tapestry biobank.

The underlying figure is generated by an internal script (data not public).
This passthrough copies the pre-generated figure from evee_resubmission_natgen/
to figures/figure1/ for manuscript assembly.

Source: evee_resubmission_natgen/fig_ldlr_severity_roc.{png,pdf}
Output: figures/figure1/fig1g_ldlr_severity.{png,pdf}

The per-tier violin distribution is moved to supplement (supfig_ldlr_severity_violin).
"""
import shutil
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT))

SRC_DIR = ROOT / "evee_resubmission_natgen"
OUT_DIR = ROOT / "figures" / "figure1"
OUT_DIR.mkdir(parents=True, exist_ok=True)

STEM = "fig_ldlr_severity_roc"
OUT_STEM = "fig1g_ldlr_severity"


def main():
    for ext in ("png", "pdf"):
        src = SRC_DIR / f"{STEM}.{ext}"
        dst = OUT_DIR / f"{OUT_STEM}.{ext}"
        if not src.exists():
            raise FileNotFoundError(f"Source not found: {src}")
        shutil.copy2(src, dst)
        print(f"Copied: {dst}")


if __name__ == "__main__":
    main()
