#!/usr/bin/env python3
"""
Fig 2D — Cross-gene mechanism-class recovery (EVEE vs baselines).

Grouped bar plot of 5-fold CV balanced accuracy for recovering documented
allelic-series mechanism classes across LDLR, LMNA, MYH7, and TP53.
EVEE + position mean BA = 0.79 vs 0.51 (position only), 0.33 (AlphaMissense),
0.26 (CADD).

The underlying figure is generated by an internal script (data not public).
This passthrough copies the pre-generated figure from evee_resubmission_natgen/
to figures/figure2/ for manuscript assembly.

Source: evee_resubmission_natgen/fig_mechanism_recovery.{png,pdf}
Output: figures/figure2/fig2d_mechanism_recovery.{png,pdf}
"""
import shutil
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]

SRC_DIR  = ROOT / "evee_resubmission_natgen"
OUT_DIR  = ROOT / "figures" / "figure2"
OUT_DIR.mkdir(parents=True, exist_ok=True)

STEM     = "fig_mechanism_recovery"
OUT_STEM = "fig2d_mechanism_recovery"


def main():
    for ext in ("png", "pdf"):
        src = SRC_DIR / f"{STEM}.{ext}"
        dst = OUT_DIR / f"{OUT_STEM}.{ext}"
        if not src.exists():
            raise FileNotFoundError(f"Source not found: {src}")
        shutil.copy2(src, dst)
        print(f"Copied: {dst}")


if __name__ == "__main__":
    main()
